// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

namespace NotissimusTest
{
    /// <remarks />
    [GeneratedCode("System.Xml", "4.0.30319.17020")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class yml_catalog
    {
        private string dateField;

        private shop shopField;

        /// <remarks />
        [XmlAttribute]
        public string date
        {
            get { return dateField; }
            set { dateField = value; }
        }

        /// <remarks />
        public shop shop
        {
            get { return shopField; }
            set { shopField = value; }
        }
    }

    /// <remarks />
    [GeneratedCode("System.Xml", "4.0.30319.17020")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot(Namespace = "", IsNullable = true)]
    public class shop
    {
        private string adultField;
        private string agencyField;

        private category[] categoriesField;
        private string companyField;
        private currency[] currenciesField;

        private string deliveryField;

        private deliveryIncluded deliveryIncludedField;
        private string[] emailField;

        private string local_delivery_costField;
        private string nameField;

        private offer[] offersField;
        private string phoneField;
        private string pickupField;
        private string platformField;
        private string storeField;
        private string urlField;
        private string versionField;

        /// <remarks />
        public string name
        {
            get { return nameField; }
            set { nameField = value; }
        }

        /// <remarks />
        public string company
        {
            get { return companyField; }
            set { companyField = value; }
        }

        /// <remarks />
        public string url
        {
            get { return urlField; }
            set { urlField = value; }
        }

        /// <remarks />
        public string phone
        {
            get { return phoneField; }
            set { phoneField = value; }
        }

        /// <remarks />
        public string platform
        {
            get { return platformField; }
            set { platformField = value; }
        }

        /// <remarks />
        public string version
        {
            get { return versionField; }
            set { versionField = value; }
        }

        /// <remarks />
        public string agency
        {
            get { return agencyField; }
            set { agencyField = value; }
        }

        /// <remarks />
        [XmlElement("email")]
        public string[] email
        {
            get { return emailField; }
            set { emailField = value; }
        }

        /// <remarks />
        [XmlArrayItem(IsNullable = false)]
        public currency[] currencies
        {
            get { return currenciesField; }
            set { currenciesField = value; }
        }

        /// <remarks />
        [XmlArrayItem(IsNullable = false)]
        public category[] categories
        {
            get { return categoriesField; }
            set { categoriesField = value; }
        }

        /// <remarks />
        public string store
        {
            get { return storeField; }
            set { storeField = value; }
        }

        /// <remarks />
        public string pickup
        {
            get { return pickupField; }
            set { pickupField = value; }
        }

        /// <remarks />
        public string delivery
        {
            get { return deliveryField; }
            set { deliveryField = value; }
        }

        /// <remarks />
        public deliveryIncluded deliveryIncluded
        {
            get { return deliveryIncludedField; }
            set { deliveryIncludedField = value; }
        }

        /// <remarks />
        public string local_delivery_cost
        {
            get { return local_delivery_costField; }
            set { local_delivery_costField = value; }
        }

        /// <remarks />
        public string adult
        {
            get { return adultField; }
            set { adultField = value; }
        }

        /// <remarks />
        [XmlArrayItem(IsNullable = false)]
        public offer[] offers
        {
            get { return offersField; }
            set { offersField = value; }
        }
    }

    /// <remarks />
    [GeneratedCode("System.Xml", "4.0.30319.17020")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot(Namespace = "", IsNullable = true)]
    public class currency
    {
        private currencyId idField;

        private string plusField;
        private string rateField;

        /// <remarks />
        [XmlAttribute]
        public currencyId id
        {
            get { return idField; }
            set { idField = value; }
        }

        /// <remarks />
        [DefaultValue("1")]
        [XmlAttribute]
        public string rate
        {
            get { return rateField; }
            set { rateField = value; }
        }

        /// <remarks />
        [DefaultValue("0")]
        [XmlAttribute]
        public string plus
        {
            get { return plusField; }
            set { plusField = value; }
        }
    }

    /// <remarks />
    [GeneratedCode("System.Xml", "4.0.30319.17020")]
    [Serializable]
    public enum currencyId
    {
        /// <remarks />
        RUR,

        /// <remarks />
        RUB,

        /// <remarks />
        USD,

        /// <remarks />
        BYR,

        /// <remarks />
        KZT,

        /// <remarks />
        EUR,

        /// <remarks />
        UAH,
    }

    /// <remarks />
    [GeneratedCode("System.Xml", "4.0.30319.17020")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot(Namespace = "", IsNullable = true)]
    public class category
    {
        private string idField1;

        private string parentIdField;

        private string tidField;

        private string valueField;
        private string yidField;

        /// <remarks />
        [XmlAttribute]
        public string id
        {
            get { return idField1; }
            set { idField1 = value; }
        }

        /// <remarks />
        [XmlAttribute]
        public string parentId
        {
            get { return parentIdField; }
            set { parentIdField = value; }
        }

        /// <remarks />
        [XmlAttribute]
        public string tid
        {
            get { return tidField; }
            set { tidField = value; }
        }

        /// <remarks />
        [XmlAttribute]
        public string yid
        {
            get { return yidField; }
            set { yidField = value; }
        }

        /// <remarks />
        [XmlText]
        public string Value
        {
            get { return valueField; }
            set { valueField = value; }
        }
    }

    /// <remarks />
    [GeneratedCode("System.Xml", "4.0.30319.17020")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot(Namespace = "", IsNullable = true)]
    public class deliveryIncluded
    {
    }

    /// <remarks />
    [GeneratedCode("System.Xml", "4.0.30319.17020")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot(Namespace = "", IsNullable = true)]
    public class offer
    {
        private string[] additionalField;
        private string adultField1;

        private string ageField;
        private string aliasesField;
        private offerAvailable availableField;

        private bool availableSpecifiedField;
        private string[] barcodeField;

        private string bidField;

        private string buyurlField;

        private categoryId[] categoryIdField;
        private string cbidField;
        private string country_of_originField;
        private string currencyIdField;

        private string deliveryField1;

        private deliveryIncluded deliveryIncludedField1;
        private string descriptionField;
        private string downloadableField;
        private string group_idField;
        private string idField2;

        private ItemsChoiceType[] itemsElementNameField;

        private object[] itemsField;
        private string local_delivery_costField1;

        private string manufacturer_warrantyField;
        private string market_categoryField;
        private orderingTime orderingTimeField;

        private param[] paramField;
        private string pickupField1;
        private string[] pictureField;
        private string priceField;
        private string promoField;

        private string[] related_offerField;
        private string sales_notesField;
        private string storeField1;
        private offerType typeField;

        private bool typeSpecifiedField;
        private string urlField1;
        private string wpriceField;
        private string xCategoryField;

        /// <remarks />
        [XmlAttribute]
        public string id
        {
            get { return idField2; }
            set { idField2 = value; }
        }

        /// <remarks />
        [XmlAttribute]
        public string group_id
        {
            get { return group_idField; }
            set { group_idField = value; }
        }

        /// <remarks />
        [XmlAttribute]
        public offerType type
        {
            get { return typeField; }
            set { typeField = value; }
        }

        /// <remarks />
        [XmlIgnore]
        public virtual bool typeSpecified
        {
            get { return typeSpecifiedField; }
            set { typeSpecifiedField = value; }
        }

        /// <remarks />
        [XmlAttribute]
        public offerAvailable available
        {
            get { return availableField; }
            set { availableField = value; }
        }

        /// <remarks />
        [XmlIgnore]
        public virtual bool availableSpecified
        {
            get { return availableSpecifiedField; }
            set { availableSpecifiedField = value; }
        }

        /// <remarks />
        [XmlAttribute]
        public string bid
        {
            get { return bidField; }
            set { bidField = value; }
        }

        /// <remarks />
        [XmlAttribute]
        public string cbid
        {
            get { return cbidField; }
            set { cbidField = value; }
        }

        /// <remarks />
        public string url
        {
            get { return urlField1; }
            set { urlField1 = value; }
        }

        /// <remarks />
        public string buyurl
        {
            get { return buyurlField; }
            set { buyurlField = value; }
        }

        /// <remarks />
        public string price
        {
            get { return priceField; }
            set { priceField = value; }
        }

        /// <remarks />
        public string wprice
        {
            get { return wpriceField; }
            set { wpriceField = value; }
        }

        /// <remarks />
        public string currencyId
        {
            get { return currencyIdField; }
            set { currencyIdField = value; }
        }

        /// <remarks />
        public string xCategory
        {
            get { return xCategoryField; }
            set { xCategoryField = value; }
        }

        /// <remarks />
        [XmlElement("categoryId")]
        public categoryId[] categoryId
        {
            get { return categoryIdField; }
            set { categoryIdField = value; }
        }

        /// <remarks />
        public string market_category
        {
            get { return market_categoryField; }
            set { market_categoryField = value; }
        }

        /// <remarks />
        [XmlElement("picture")]
        public string[] picture
        {
            get { return pictureField; }
            set { pictureField = value; }
        }

        /// <remarks />
        public string store
        {
            get { return storeField1; }
            set { storeField1 = value; }
        }

        /// <remarks />
        public string pickup
        {
            get { return pickupField1; }
            set { pickupField1 = value; }
        }

        /// <remarks />
        public string delivery
        {
            get { return deliveryField1; }
            set { deliveryField1 = value; }
        }

        /// <remarks />
        public deliveryIncluded deliveryIncluded
        {
            get { return deliveryIncludedField1; }
            set { deliveryIncludedField1 = value; }
        }

        /// <remarks />
        public string local_delivery_cost
        {
            get { return local_delivery_costField1; }
            set { local_delivery_costField1 = value; }
        }

        /// <remarks />
        public orderingTime orderingTime
        {
            get { return orderingTimeField; }
            set { orderingTimeField = value; }
        }

        /// <remarks />
        [XmlIgnore]
        public ItemsChoiceType[] ItemsElementName
        {
            get { return itemsElementNameField; }
            set { itemsElementNameField = value; }
        }

        /// <remarks />
        [XmlElement("typePrefix", Type = typeof (string))]
        [XmlElement("vendor", Type = typeof (string))]
        [XmlElement("vendorCode", Type = typeof (string))]
        [XmlElement("model", Type = typeof (string))]
        [XmlElement("provider", Type = typeof (string))]
        [XmlElement("tarifplan", Type = typeof (string))]
        [XmlElement("author", Type = typeof (string))]
        [XmlElement("name", Type = typeof (string))]
        [XmlElement("publisher", Type = typeof (string))]
        [XmlElement("series", Type = typeof (string))]
        [XmlElement("year", Type = typeof (string))]
        [XmlElement("ISBN", Type = typeof (string))]
        [XmlElement("volume", Type = typeof (string))]
        [XmlElement("part", Type = typeof (string))]
        [XmlElement("language", Type = typeof (string))]
        [XmlElement("binding", Type = typeof (string))]
        [XmlElement("page_extent", Type = typeof (string))]
        [XmlElement("table_of_contents", Type = typeof (string))]
        [XmlElement("performed_by", Type = typeof (string))]
        [XmlElement("performance_type", Type = typeof (string))]
        [XmlElement("storage", Type = typeof (string))]
        [XmlElement("format", Type = typeof (string))]
        [XmlElement("recording_length", Type = typeof (string))]
        [XmlElement("artist", Type = typeof (string))]
        [XmlElement("title", Type = typeof (string))]
        [XmlElement("media", Type = typeof (string))]
        [XmlElement("starring", Type = typeof (string))]
        [XmlElement("director", Type = typeof (string))]
        [XmlElement("originalName", Type = typeof (string))]
        [XmlElement("country", Type = typeof (string))]
        [XmlElement("worldRegion", Type = typeof (string))]
        [XmlElement("region", Type = typeof (string))]
        [XmlElement("days", Type = typeof (string))]
        [XmlElement("dataTour", Type = typeof (string))]
        [XmlElement("hotel_stars", Type = typeof (string))]
        [XmlElement("room", Type = typeof (string))]
        [XmlElement("meal", Type = typeof (string))]
        [XmlElement("included", Type = typeof (string))]
        [XmlElement("transport", Type = typeof (string))]
        [XmlElement("price_min", Type = typeof (string))]
        [XmlElement("price_max", Type = typeof (string))]
        [XmlElement("options", Type = typeof (string))]
        [XmlElement("place", Type = typeof (string))]
        [XmlElement("hall", Type = typeof (hall))]
        [XmlElement("hall_part", Type = typeof (string))]
        [XmlElement("date", Type = typeof (string))]
        [XmlElement("is_premiere", Type = typeof (string))]
        [XmlElement("is_kids", Type = typeof (string))]
        [XmlChoiceIdentifier("ItemsElementName")]
        public object[] Items
        {
            get { return itemsField; }
            set { itemsField = value; }
        }

        /// <remarks />
        public string aliases
        {
            get { return aliasesField; }
            set { aliasesField = value; }
        }

        /// <remarks />
        [XmlElement("additional")]
        public string[] additional
        {
            get { return additionalField; }
            set { additionalField = value; }
        }

        /// <remarks />
        public string description
        {
            get { return descriptionField; }
            set { descriptionField = value; }
        }

        /// <remarks />
        public string sales_notes
        {
            get { return sales_notesField; }
            set { sales_notesField = value; }
        }

        /// <remarks />
        public string promo
        {
            get { return promoField; }
            set { promoField = value; }
        }

        /// <remarks />
        public string manufacturer_warranty
        {
            get { return manufacturer_warrantyField; }
            set { manufacturer_warrantyField = value; }
        }

        /// <remarks />
        public string country_of_origin
        {
            get { return country_of_originField; }
            set { country_of_originField = value; }
        }

        /// <remarks />
        public string downloadable
        {
            get { return downloadableField; }
            set { downloadableField = value; }
        }

        /// <remarks />
        public string adult
        {
            get { return adultField1; }
            set { adultField1 = value; }
        }

        /// <remarks />
        public string age
        {
            get { return ageField; }
            set { ageField = value; }
        }

        /// <remarks />
        [XmlElement("barcode")]
        public string[] barcode
        {
            get { return barcodeField; }
            set { barcodeField = value; }
        }

        /// <remarks />
        [XmlElement("param")]
        public param[] param
        {
            get { return paramField; }
            set { paramField = value; }
        }

        /// <remarks />
        [XmlElement("related_offer")]
        public string[] related_offer
        {
            get { return related_offerField; }
            set { related_offerField = value; }
        }
    }

    /// <remarks />
    [GeneratedCode("System.Xml", "4.0.30319.17020")]
    [Serializable]
    public enum offerType
    {
        /// <remarks />
        [XmlEnum("vendor.model")] vendormodel,

        /// <remarks />
        book,

        /// <remarks />
        audiobook,

        /// <remarks />
        [XmlEnum("artist.title")] artisttitle,

        /// <remarks />
        tour,

        /// <remarks />
        ticket,

        /// <remarks />
        [XmlEnum("event-ticket")] eventticket,
    }

    /// <remarks />
    [GeneratedCode("System.Xml", "4.0.30319.17020")]
    [Serializable]
    public enum offerAvailable
    {
        /// <remarks />
        @true,

        /// <remarks />
        @false,
    }

    /// <remarks />
    [GeneratedCode("System.Xml", "4.0.30319.17020")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot(Namespace = "", IsNullable = true)]
    public class categoryId
    {
        private categoryIdType typeField1;

        private string valueField1;

        /// <remarks />
        [DefaultValue(categoryIdType.Own)]
        [XmlAttribute]
        public categoryIdType type
        {
            get { return typeField1; }
            set { typeField1 = value; }
        }

        /// <remarks />
        [XmlText]
        public string Value
        {
            get { return valueField1; }
            set { valueField1 = value; }
        }
    }

    /// <remarks />
    [GeneratedCode("System.Xml", "4.0.30319.17020")]
    [Serializable]
    public enum categoryIdType
    {
        /// <remarks />
        Yandex,

        /// <remarks />
        Torg,

        /// <remarks />
        Own,
    }

    /// <remarks />
    [GeneratedCode("System.Xml", "4.0.30319.17020")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot(Namespace = "", IsNullable = true)]
    public class orderingTime
    {
        private deliveryTime deliveryTimeField;
        private onstock onstockField;

        private ordering orderingField;

        /// <remarks />
        public onstock onstock
        {
            get { return onstockField; }
            set { onstockField = value; }
        }

        /// <remarks />
        public ordering ordering
        {
            get { return orderingField; }
            set { orderingField = value; }
        }

        /// <remarks />
        public deliveryTime deliveryTime
        {
            get { return deliveryTimeField; }
            set { deliveryTimeField = value; }
        }
    }

    /// <remarks />
    [GeneratedCode("System.Xml", "4.0.30319.17020")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot(Namespace = "", IsNullable = true)]
    public class onstock
    {
    }

    /// <remarks />
    [GeneratedCode("System.Xml", "4.0.30319.17020")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot(Namespace = "", IsNullable = true)]
    public class ordering
    {
        private string hoursField;

        private string valueField2;

        /// <remarks />
        [XmlAttribute]
        public string hours
        {
            get { return hoursField; }
            set { hoursField = value; }
        }

        /// <remarks />
        [XmlText]
        public string Value
        {
            get { return valueField2; }
            set { valueField2 = value; }
        }
    }

    /// <remarks />
    [GeneratedCode("System.Xml", "4.0.30319.17020")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot(Namespace = "", IsNullable = true)]
    public class deliveryTime
    {
    }

    /// <remarks />
    [GeneratedCode("System.Xml", "4.0.30319.17020")]
    [Serializable]
    [XmlType(IncludeInSchema = false)]
    public enum ItemsChoiceType
    {
        /// <remarks />
        typePrefix,

        /// <remarks />
        vendor,

        /// <remarks />
        vendorCode,

        /// <remarks />
        model,

        /// <remarks />
        provider,

        /// <remarks />
        tarifplan,

        /// <remarks />
        author,

        /// <remarks />
        name,

        /// <remarks />
        publisher,

        /// <remarks />
        series,

        /// <remarks />
        year,

        /// <remarks />
        ISBN,

        /// <remarks />
        volume,

        /// <remarks />
        part,

        /// <remarks />
        language,

        /// <remarks />
        binding,

        /// <remarks />
        page_extent,

        /// <remarks />
        table_of_contents,

        /// <remarks />
        performed_by,

        /// <remarks />
        performance_type,

        /// <remarks />
        storage,

        /// <remarks />
        format,

        /// <remarks />
        recording_length,

        /// <remarks />
        artist,

        /// <remarks />
        title,

        /// <remarks />
        media,

        /// <remarks />
        starring,

        /// <remarks />
        director,

        /// <remarks />
        originalName,

        /// <remarks />
        country,

        /// <remarks />
        worldRegion,

        /// <remarks />
        region,

        /// <remarks />
        days,

        /// <remarks />
        dataTour,

        /// <remarks />
        hotel_stars,

        /// <remarks />
        room,

        /// <remarks />
        meal,

        /// <remarks />
        included,

        /// <remarks />
        transport,

        /// <remarks />
        price_min,

        /// <remarks />
        price_max,

        /// <remarks />
        options,

        /// <remarks />
        place,

        /// <remarks />
        hall,

        /// <remarks />
        hall_part,

        /// <remarks />
        date,

        /// <remarks />
        is_premiere,

        /// <remarks />
        is_kids,
    }

    /// <remarks />
    [GeneratedCode("System.Xml", "4.0.30319.17020")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot(Namespace = "", IsNullable = true)]
    public class hall
    {
        private string planField;

        private string valueField3;

        /// <remarks />
        [XmlAttribute]
        public string plan
        {
            get { return planField; }
            set { planField = value; }
        }

        /// <remarks />
        [XmlText]
        public string Value
        {
            get { return valueField3; }
            set { valueField3 = value; }
        }
    }

    /// <remarks />
    [GeneratedCode("System.Xml", "4.0.30319.17020")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot(Namespace = "", IsNullable = true)]
    public class param
    {
        private string nameField1;

        private string unitField;

        private string valueField4;

        /// <remarks />
        [XmlAttribute]
        public string name
        {
            get { return nameField1; }
            set { nameField1 = value; }
        }

        /// <remarks />
        [XmlAttribute]
        public string unit
        {
            get { return unitField; }
            set { unitField = value; }
        }

        /// <remarks />
        [XmlText]
        public string Value
        {
            get { return valueField4; }
            set { valueField4 = value; }
        }
    }
}