// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace NotissimusTest
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class yml_catalog {
        
        private string dateField;
        
        private shop shopField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public shop shop {
            get {
                return this.shopField;
            }
            set {
                this.shopField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class shop {
        
        private string nameField;
        
        private string companyField;
        
        private string urlField;
        
        private string phoneField;
        
        private string platformField;
        
        private string versionField;
        
        private string agencyField;
        
        private string[] emailField;
        
        private currency[] currenciesField;
        
        private category[] categoriesField;
        
        private string storeField;
        
        private string pickupField;
        
        private string deliveryField;
        
        private deliveryIncluded deliveryIncludedField;
        
        private string local_delivery_costField;
        
        private string adultField;
        
        private offer[] offersField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string platform {
            get {
                return this.platformField;
            }
            set {
                this.platformField = value;
            }
        }
        
        /// <remarks/>
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public string agency {
            get {
                return this.agencyField;
            }
            set {
                this.agencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("email")]
        public string[] email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public currency[] currencies {
            get {
                return this.currenciesField;
            }
            set {
                this.currenciesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public category[] categories {
            get {
                return this.categoriesField;
            }
            set {
                this.categoriesField = value;
            }
        }
        
        /// <remarks/>
        public string store {
            get {
                return this.storeField;
            }
            set {
                this.storeField = value;
            }
        }
        
        /// <remarks/>
        public string pickup {
            get {
                return this.pickupField;
            }
            set {
                this.pickupField = value;
            }
        }
        
        /// <remarks/>
        public string delivery {
            get {
                return this.deliveryField;
            }
            set {
                this.deliveryField = value;
            }
        }
        
        /// <remarks/>
        public deliveryIncluded deliveryIncluded {
            get {
                return this.deliveryIncludedField;
            }
            set {
                this.deliveryIncludedField = value;
            }
        }
        
        /// <remarks/>
        public string local_delivery_cost {
            get {
                return this.local_delivery_costField;
            }
            set {
                this.local_delivery_costField = value;
            }
        }
        
        /// <remarks/>
        public string adult {
            get {
                return this.adultField;
            }
            set {
                this.adultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public offer[] offers {
            get {
                return this.offersField;
            }
            set {
                this.offersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class currency {
        
        private currencyId idField;
        
        private string rateField;
        
        private string plusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public currencyId id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValue("1")]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValue("0")]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string plus {
            get {
                return this.plusField;
            }
            set {
                this.plusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    public enum currencyId {
        
        /// <remarks/>
        RUR,
        
        /// <remarks/>
        RUB,
        
        /// <remarks/>
        USD,
        
        /// <remarks/>
        BYR,
        
        /// <remarks/>
        KZT,
        
        /// <remarks/>
        EUR,
        
        /// <remarks/>
        UAH,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class category {
        
        private string idField1;
        
        private string parentIdField;
        
        private string tidField;
        
        private string yidField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField1;
            }
            set {
                this.idField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string parentId {
            get {
                return this.parentIdField;
            }
            set {
                this.parentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tid {
            get {
                return this.tidField;
            }
            set {
                this.tidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string yid {
            get {
                return this.yidField;
            }
            set {
                this.yidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class deliveryIncluded {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class offer {
        
        private string idField2;
        
        private string group_idField;
        
        private offerType typeField;
        
        private bool typeSpecifiedField;
        
        private offerAvailable availableField;
        
        private bool availableSpecifiedField;
        
        private string bidField;
        
        private string cbidField;
        
        private string urlField1;
        
        private string buyurlField;
        
        private string priceField;
        
        private string wpriceField;
        
        private string currencyIdField;
        
        private string xCategoryField;
        
        private categoryId[] categoryIdField;
        
        private string market_categoryField;
        
        private string[] pictureField;
        
        private string storeField1;
        
        private string pickupField1;
        
        private string deliveryField1;
        
        private deliveryIncluded deliveryIncludedField1;
        
        private string local_delivery_costField1;
        
        private orderingTime orderingTimeField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        private object[] itemsField;
        
        private string aliasesField;
        
        private string[] additionalField;
        
        private string descriptionField;
        
        private string sales_notesField;
        
        private string promoField;
        
        private string manufacturer_warrantyField;
        
        private string country_of_originField;
        
        private string downloadableField;
        
        private string adultField1;
        
        private string ageField;
        
        private string[] barcodeField;
        
        private param[] paramField;
        
        private string[] related_offerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField2;
            }
            set {
                this.idField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string group_id {
            get {
                return this.group_idField;
            }
            set {
                this.group_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public offerType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool typeSpecified {
            get {
                return this.typeSpecifiedField;
            }
            set {
                this.typeSpecifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public offerAvailable available {
            get {
                return this.availableField;
            }
            set {
                this.availableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool availableSpecified {
            get {
                return this.availableSpecifiedField;
            }
            set {
                this.availableSpecifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bid {
            get {
                return this.bidField;
            }
            set {
                this.bidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string cbid {
            get {
                return this.cbidField;
            }
            set {
                this.cbidField = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField1;
            }
            set {
                this.urlField1 = value;
            }
        }
        
        /// <remarks/>
        public string buyurl {
            get {
                return this.buyurlField;
            }
            set {
                this.buyurlField = value;
            }
        }
        
        /// <remarks/>
        public string price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public string wprice {
            get {
                return this.wpriceField;
            }
            set {
                this.wpriceField = value;
            }
        }
        
        /// <remarks/>
        public string currencyId {
            get {
                return this.currencyIdField;
            }
            set {
                this.currencyIdField = value;
            }
        }
        
        /// <remarks/>
        public string xCategory {
            get {
                return this.xCategoryField;
            }
            set {
                this.xCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("categoryId")]
        public categoryId[] categoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
            }
        }
        
        /// <remarks/>
        public string market_category {
            get {
                return this.market_categoryField;
            }
            set {
                this.market_categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("picture")]
        public string[] picture {
            get {
                return this.pictureField;
            }
            set {
                this.pictureField = value;
            }
        }
        
        /// <remarks/>
        public string store {
            get {
                return this.storeField1;
            }
            set {
                this.storeField1 = value;
            }
        }
        
        /// <remarks/>
        public string pickup {
            get {
                return this.pickupField1;
            }
            set {
                this.pickupField1 = value;
            }
        }
        
        /// <remarks/>
        public string delivery {
            get {
                return this.deliveryField1;
            }
            set {
                this.deliveryField1 = value;
            }
        }
        
        /// <remarks/>
        public deliveryIncluded deliveryIncluded {
            get {
                return this.deliveryIncludedField1;
            }
            set {
                this.deliveryIncludedField1 = value;
            }
        }
        
        /// <remarks/>
        public string local_delivery_cost {
            get {
                return this.local_delivery_costField1;
            }
            set {
                this.local_delivery_costField1 = value;
            }
        }
        
        /// <remarks/>
        public orderingTime orderingTime {
            get {
                return this.orderingTimeField;
            }
            set {
                this.orderingTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("typePrefix", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("vendor", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("vendorCode", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("model", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("provider", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("tarifplan", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("author", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("name", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("publisher", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("series", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("year", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ISBN", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("volume", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("part", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("language", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("binding", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("page_extent", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("table_of_contents", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("performed_by", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("performance_type", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("storage", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("format", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("recording_length", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("artist", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("title", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("media", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("starring", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("director", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("originalName", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("country", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("worldRegion", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("region", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("days", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("dataTour", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("hotel_stars", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("room", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("meal", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("included", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("transport", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("price_min", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("price_max", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("options", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("place", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("hall", Type=typeof(hall))]
        [System.Xml.Serialization.XmlElementAttribute("hall_part", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("date", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("is_premiere", Type=typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("is_kids", Type=typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifier("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        public string aliases {
            get {
                return this.aliasesField;
            }
            set {
                this.aliasesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("additional")]
        public string[] additional {
            get {
                return this.additionalField;
            }
            set {
                this.additionalField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string sales_notes {
            get {
                return this.sales_notesField;
            }
            set {
                this.sales_notesField = value;
            }
        }
        
        /// <remarks/>
        public string promo {
            get {
                return this.promoField;
            }
            set {
                this.promoField = value;
            }
        }
        
        /// <remarks/>
        public string manufacturer_warranty {
            get {
                return this.manufacturer_warrantyField;
            }
            set {
                this.manufacturer_warrantyField = value;
            }
        }
        
        /// <remarks/>
        public string country_of_origin {
            get {
                return this.country_of_originField;
            }
            set {
                this.country_of_originField = value;
            }
        }
        
        /// <remarks/>
        public string downloadable {
            get {
                return this.downloadableField;
            }
            set {
                this.downloadableField = value;
            }
        }
        
        /// <remarks/>
        public string adult {
            get {
                return this.adultField1;
            }
            set {
                this.adultField1 = value;
            }
        }
        
        /// <remarks/>
        public string age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("barcode")]
        public string[] barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("param")]
        public param[] param {
            get {
                return this.paramField;
            }
            set {
                this.paramField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("related_offer")]
        public string[] related_offer {
            get {
                return this.related_offerField;
            }
            set {
                this.related_offerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    public enum offerType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("vendor.model")]
        vendormodel,
        
        /// <remarks/>
        book,
        
        /// <remarks/>
        audiobook,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("artist.title")]
        artisttitle,
        
        /// <remarks/>
        tour,
        
        /// <remarks/>
        ticket,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("event-ticket")]
        eventticket,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    public enum offerAvailable {
        
        /// <remarks/>
        @true,
        
        /// <remarks/>
        @false,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class categoryId {
        
        private categoryIdType typeField1;
        
        private string valueField1;
        
        /// <remarks/>
        [System.ComponentModel.DefaultValue(categoryIdType.Own)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public categoryIdType type {
            get {
                return this.typeField1;
            }
            set {
                this.typeField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField1;
            }
            set {
                this.valueField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    public enum categoryIdType {
        
        /// <remarks/>
        Yandex,
        
        /// <remarks/>
        Torg,
        
        /// <remarks/>
        Own,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class orderingTime {
        
        private onstock onstockField;
        
        private ordering orderingField;
        
        private deliveryTime deliveryTimeField;
        
        /// <remarks/>
        public onstock onstock {
            get {
                return this.onstockField;
            }
            set {
                this.onstockField = value;
            }
        }
        
        /// <remarks/>
        public ordering ordering {
            get {
                return this.orderingField;
            }
            set {
                this.orderingField = value;
            }
        }
        
        /// <remarks/>
        public deliveryTime deliveryTime {
            get {
                return this.deliveryTimeField;
            }
            set {
                this.deliveryTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class onstock {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class ordering {
        
        private string hoursField;
        
        private string valueField2;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string hours {
            get {
                return this.hoursField;
            }
            set {
                this.hoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField2;
            }
            set {
                this.valueField2 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class deliveryTime {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        typePrefix,
        
        /// <remarks/>
        vendor,
        
        /// <remarks/>
        vendorCode,
        
        /// <remarks/>
        model,
        
        /// <remarks/>
        provider,
        
        /// <remarks/>
        tarifplan,
        
        /// <remarks/>
        author,
        
        /// <remarks/>
        name,
        
        /// <remarks/>
        publisher,
        
        /// <remarks/>
        series,
        
        /// <remarks/>
        year,
        
        /// <remarks/>
        ISBN,
        
        /// <remarks/>
        volume,
        
        /// <remarks/>
        part,
        
        /// <remarks/>
        language,
        
        /// <remarks/>
        binding,
        
        /// <remarks/>
        page_extent,
        
        /// <remarks/>
        table_of_contents,
        
        /// <remarks/>
        performed_by,
        
        /// <remarks/>
        performance_type,
        
        /// <remarks/>
        storage,
        
        /// <remarks/>
        format,
        
        /// <remarks/>
        recording_length,
        
        /// <remarks/>
        artist,
        
        /// <remarks/>
        title,
        
        /// <remarks/>
        media,
        
        /// <remarks/>
        starring,
        
        /// <remarks/>
        director,
        
        /// <remarks/>
        originalName,
        
        /// <remarks/>
        country,
        
        /// <remarks/>
        worldRegion,
        
        /// <remarks/>
        region,
        
        /// <remarks/>
        days,
        
        /// <remarks/>
        dataTour,
        
        /// <remarks/>
        hotel_stars,
        
        /// <remarks/>
        room,
        
        /// <remarks/>
        meal,
        
        /// <remarks/>
        included,
        
        /// <remarks/>
        transport,
        
        /// <remarks/>
        price_min,
        
        /// <remarks/>
        price_max,
        
        /// <remarks/>
        options,
        
        /// <remarks/>
        place,
        
        /// <remarks/>
        hall,
        
        /// <remarks/>
        hall_part,
        
        /// <remarks/>
        date,
        
        /// <remarks/>
        is_premiere,
        
        /// <remarks/>
        is_kids,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class hall {
        
        private string planField;
        
        private string valueField3;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string plan {
            get {
                return this.planField;
            }
            set {
                this.planField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField3;
            }
            set {
                this.valueField3 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class param {
        
        private string nameField1;
        
        private string unitField;
        
        private string valueField4;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField1;
            }
            set {
                this.nameField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField4;
            }
            set {
                this.valueField4 = value;
            }
        }
    }
}
